#pragma once
//Spielfeld
#define SPIELFELD_SYMBOL_GRENZE '*' 
#define SPIELFELD_SYMBOL_MITTEL '|'
#define SPIELFELD_OFFSET_Y 3
#define SPIELFELD_OFFSET_X 5
#define SPIELFELD_YSIZE 30
#define SPIELFELD_XSIZE 80
//Spieler
#define SPIELER_1 1
#define SPIELER_2 2
#define SPIELER_SYMBOL '#'
#define SPIELER_BREITE 2
#define SPIELER_HOEHE 5
#define SPIELER_1_XPOS SPIELFELD_OFFSET_X+3
#define SPIELER_2_XPOS SPIELFELD_OFFSET_X+SPIELFELD_XSIZE-SPIELER_BREITE-3
#define SPIELER_YPOS SPIELFELD_OFFSET_Y+(SPIELFELD_YSIZE-SPIELER_HOEHE)/2
#define SPIELER_1_HOCH 'w'
#define SPIELER_1_LINKS 'a'
#define SPIELER_1_RUNTER 's'
#define SPIELER_1_RECHTS 'd'
#define SPIELER_2_HOCH '8'
#define SPIELER_2_LINKS '4'
#define SPIELER_2_RUNTER '5'
#define SPIELER_2_RECHTS '6'
//Ball
#define BALL_SYMBOL 'O'
#define BALL_BREITE 2
#define BALL_HOEHE 2
#define BALL_XPOS_START SPIELFELD_OFFSET_X+(SPIELFELD_XSIZE+BALL_BREITE)/2
#define BALL_YPOS_START SPIELFELD_OFFSET_Y+(SPIELFELD_YSIZE+BALL_HOEHE)/2
//Punktestand
#define PUNKTSTAND_XPOS SPIELFELD_OFFSET_X + SPIELFELD_XSIZE / 2 - 8;
#define PUNKTSTAND_YPOS SPIELFELD_OFFSET_Y + 3;
//Bewegung
#define BEWEGUNG_HOCH 0
#define BEWEGUNG_LINKS 1
#define BEWEGUNG_RUNTER 2
#define BEWEGUNG_RECHTS 3
//Punktestand
#define EINS 1
#define ZWEI 2
#define DREI 3
#define VIER 4
#define FUENF 5
#define SECHS 6
#define SIEBEN 7
#define ACHT 8
#define NEUN 9
#define DPUNKT 10
#define LEER 11